"""baseline schema

Revision ID: 322c0bd713df
Revises: 
Create Date: 2025-10-21 20:24:01.461259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322c0bd713df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_campus'), ['campus'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_location_name'), ['name'], unique=False)
        batch_op.create_index('uq_location_campus_name', ['campus', 'name'], unique=True)

    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_phone'), ['phone'], unique=True)

    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index('ix_resv_loc_time', ['location', 'start_time', 'end_time'], unique=False)
        batch_op.create_index('ix_resv_status_date', ['status', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index('ix_resv_status_date')
        batch_op.drop_index('ix_resv_loc_time')
        batch_op.drop_index(batch_op.f('ix_reservation_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_start_time'))
        batch_op.drop_index(batch_op.f('ix_reservation_location_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_location'))
        batch_op.drop_index(batch_op.f('ix_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_end_time'))

    op.drop_table('reservation')
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_phone'))
        batch_op.drop_index(batch_op.f('ix_visitor_id'))

    op.drop_table('visitor')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('uq_location_campus_name')
        batch_op.drop_index(batch_op.f('ix_location_name'))
        batch_op.drop_index(batch_op.f('ix_location_id'))
        batch_op.drop_index(batch_op.f('ix_location_campus'))

    op.drop_table('location')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))
        batch_op.drop_index(batch_op.f('ix_admin_id'))

    op.drop_table('admin')
    # ### end Alembic commands ###
