"""add driving info to reservation

Revision ID: c049ee67a17d
Revises: c50f40756f5b
Create Date: 2025-10-23 20:44:00.075105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c049ee67a17d'
down_revision: Union[str, Sequence[str], None] = 'c50f40756f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_driving', sa.Integer(), nullable=False,server_default='0'))
        batch_op.add_column(sa.Column('plate_number', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_plate_number'), ['plate_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_plate_number'))
        batch_op.drop_column('plate_number')
        batch_op.drop_column('is_driving')

    # ### end Alembic commands ###
