"""add admin profile fields

Revision ID: c50f40756f5b
Revises: bf0dcd0f09c7
Create Date: 2025-10-23 20:15:34.324286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50f40756f5b'
down_revision: Union[str, Sequence[str], None] = 'bf0dcd0f09c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('org', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work_address', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_phone'))
        batch_op.drop_index(batch_op.f('ix_admin_email'))
        batch_op.drop_column('work_address')
        batch_op.drop_column('email')
        batch_op.drop_column('org')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
